<?php

namespace App\Tests\Unit\Entity;

use App\Entity\AuthorRole;
use App\Entity\MangaAuthor;
use DateTime;
use PHPUnit\Framework\TestCase;

/**
 * @internal
 * @coversNothing
 */
class AuthorRoleTest extends TestCase
{
    private AuthorRole $authorRole;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->authorRole = new AuthorRole();
    }

    public function testGetRole(): void
    {
        $value = 'Auteur';
        $response = $this->authorRole->setRole($value);

        self::assertInstanceOf(AuthorRole::class, $response);
        self::assertEquals($value, $this->authorRole->getRole());
    }

    public function testGetMangaAuthors(): void
    {
        $mangaAuthor1 = new MangaAuthor();
        $mangaAuthor2 = new MangaAuthor();
        $mangaAuthor3 = new MangaAuthor();

        $this->authorRole->addMangaAuthor($mangaAuthor1);
        $this->authorRole->addMangaAuthor($mangaAuthor2);
        $this->authorRole->addMangaAuthor($mangaAuthor3);

        self::assertCount(3, $this->authorRole->getMangaAuthors());
        self::assertTrue($this->authorRole->getMangaAuthors()->contains($mangaAuthor1));
        self::assertTrue($this->authorRole->getMangaAuthors()->contains($mangaAuthor2));
        self::assertTrue($this->authorRole->getMangaAuthors()->contains($mangaAuthor3));

        $response = $this->authorRole->removeMangaAuthor($mangaAuthor3);

        self::assertInstanceOf(AuthorRole::class, $response);
        self::assertCount(2, $this->authorRole->getMangaAuthors());
        self::assertTrue($this->authorRole->getMangaAuthors()->contains($mangaAuthor1));
        self::assertTrue($this->authorRole->getMangaAuthors()->contains($mangaAuthor2));
        self::assertFalse($this->authorRole->getMangaAuthors()->contains($mangaAuthor3));
    }

    public function testGetUpdatedAt(): void
    {
        $updatedAt = new DateTime();
        $response = $this->authorRole->setUpdatedAt($updatedAt);

        self::assertInstanceOf(AuthorRole::class, $response);
        self::assertEquals($updatedAt, $this->authorRole->getUpdatedAt());
    }
}
