<?php

namespace App\Tests\Unit\Entity;

use App\Entity\Editor;
use App\Entity\EditorCollection;
use App\Entity\Manga;
use DateTime;
use PHPUnit\Framework\TestCase;

class EditorCollectionTest extends TestCase
{
    private EditorCollection $editorCollection;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->editorCollection = new EditorCollection();
    }

    public function testGetName(): void
    {
        $value = 'shonen';
        $response = $this->editorCollection->setName($value);

        self::assertInstanceOf(EditorCollection::class, $response);
        self::assertEquals($value, $this->editorCollection->getName());
    }

    public function testGetEditor(): void
    {
        $editor = new Editor();
        $response = $this->editorCollection->setEditor($editor);

        self::assertInstanceOf(EditorCollection::class, $response);
        self::assertInstanceOf(Editor::class, $this->editorCollection->getEditor());
        self::assertEquals($editor, $this->editorCollection->getEditor());
    }

    public function testGetManga(): void
    {
        $manga1 = new Manga();
        $manga2 = new Manga();
        $manga3 = new Manga();

        $this->editorCollection->addManga($manga1);
        $this->editorCollection->addManga($manga2);
        $this->editorCollection->addManga($manga3);

        self::assertCount(3, $this->editorCollection->getMangas());
        self::assertTrue($this->editorCollection->getMangas()->contains($manga1));
        self::assertTrue($this->editorCollection->getMangas()->contains($manga2));
        self::assertTrue($this->editorCollection->getMangas()->contains($manga3));

        $response = $this->editorCollection->removeManga($manga3);

        self::assertInstanceOf(EditorCollection::class, $response);
        self::assertCount(2, $this->editorCollection->getMangas());
        self::assertTrue($this->editorCollection->getMangas()->contains($manga1));
        self::assertTrue($this->editorCollection->getMangas()->contains($manga2));
        self::assertFalse($this->editorCollection->getMangas()->contains($manga3));
    }

    public function testGetUpdatedAt(): void
    {
        $updatedAt = new DateTime();
        $response = $this->editorCollection->setUpdatedAt($updatedAt);

        self::assertInstanceOf(EditorCollection::class, $response);
        self::assertEquals($updatedAt, $this->editorCollection->getUpdatedAt());
    }
}
